exceptions:
  - name: dot-prop
    platform: npm
    tests:
      - vulnerable
  - name: utest
    platform: npm
    tests:
      - unlicensed
  - name: only
    platform: npm
    tests:
      - unlicensed
